import './js/spinner';
import './js/header';
import './js/main-section';
import './js/eventLikes'
import './js/modal';
import './js/change-theme';
import './js/pagination';
import './js/closing-modal-esc';
import './js/country-list';
import './js/footer';